#  RAG Pipeline — конфигурация
#  Пути к папкам задаются в коде

_shared:
  qdrant: &qdrant
    qdrant_host: "localhost"
    qdrant_port: 6333
    qdrant_url:  ""           # если задан — host/port игнорируются
    collection_name:     "educational-rag-assistant-collection"
    dense_vector_name:   "fast-multilingual-e5-large-instruct"
    sparse_vector_name:  "fast-sparse-bm25"

  embeddings: &embeddings
    dense_model:  "intfloat/multilingual-e5-large-instruct"
    sparse_model: "Qdrant/bm25"


# Главный оркестратор
pipeline:
  # Какие этапы выполнять
  run_parser:  false
  run_chunker: true
  run_loader:  false

# Парсер
parser:
  # Какие этапы выполнять
  process_marker: false     # false → нужен готовый output_marker_processor
  process_text:   false
  process_image:  true
  one_step:       false     # true → каждый этап берёт данные только из marker-output

  # Модель
  model_name: "qwen3.5:9b"

  # Поведение
  save_intermediate: true
  delete_images:     true

# Чанкер
chunker:
  model_name: 'qwen3.5:4b'
  save_intermediate: true

# Загрузчик
loader:
  <<: [*qdrant, *embeddings]
  batch_size: 100
  vector_size: 1024

  save_intermediate: true
  recreate_db:       false

# Поиск
retriever:
  <<: [*qdrant, *embeddings]

  embedding_query_instruction: "Instruct: Найди релевантные фрагменты учебника по алгоритмам\nQuery:"

  reranker_model_name: "DiTy/cross-encoder-russian-msmarco"
  reranker_score_threshold: 0.25

  top_k_fetch: 30
  top_k_final: 3

  group_expand_score_threshold: 0.5

# Агент
agent:
  model_name: "qwen3.5:9b"
  temperature: 0.2